"""caja: medios de pago, sesiones y movimientos

Revision ID: c2ff5eb438c9
Revises: e7a79b7eee07
Create Date: 2026-08-24 19:01:10.578182

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 — lo usa el repr de JSONB

import app.core.types  # noqa: F401 — UUIDType y FlexibleJSON en las columnas

revision: str = "c2ff5eb438c9"
down_revision: str | None = "e7a79b7eee07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medio_pago",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "EFECTIVO",
                "TARJETA_DEBITO",
                "TARJETA_CREDITO",
                "QR",
                "TRANSFERENCIA",
                name="tipomediopago",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("afecta_efectivo", sa.Boolean(), nullable=False),
        sa.Column(
            "comision_porcentaje", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("dias_acreditacion", sa.Integer(), nullable=True),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medio_pago", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_medio_pago_nombre"), ["nombre"], unique=True
        )

    op.create_table(
        "sesion_caja",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "ABIERTA",
                "CERRADA",
                name="estadosesioncaja",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "fecha_apertura",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("abierta_por", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("monto_inicial", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fecha_cierre", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cerrada_por", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "efectivo_declarado", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "efectivo_esperado", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("diferencia", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("motivo_diferencia", sa.String(length=200), nullable=True),
        sa.Column("monto_retirado", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("fondo_dejado", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sesion_caja", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sesion_caja_estado"), ["estado"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sesion_caja_fecha_apertura"),
            ["fecha_apertura"],
            unique=False,
        )

    op.create_table(
        "movimiento_caja",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("sesion_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "APERTURA",
                "COBRO",
                "INGRESO",
                "RETIRO",
                "GASTO",
                "DEVOLUCION",
                "DIFERENCIA",
                "CIERRE",
                name="tipomovimientocaja",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("medio_pago_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("importe", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("concepto", sa.String(length=200), nullable=True),
        sa.Column("comprobante", sa.String(length=50), nullable=True),
        sa.Column(
            "documento_tipo",
            sa.Enum(
                "VENTA",
                "DEVOLUCION",
                "CAMBIO",
                "COMPRA",
                name="tipodocumentocaja",
                native_enum=False,
                length=15,
            ),
            nullable=True,
        ),
        sa.Column("documento_id", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["medio_pago_id"], ["medio_pago.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["sesion_id"], ["sesion_caja.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sesion_id", "numero", name="uq_movimiento_caja_numero"),
    )
    with op.batch_alter_table("movimiento_caja", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movimiento_caja_documento_id"),
            ["documento_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_movimiento_caja_medio_pago_id"),
            ["medio_pago_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_movimiento_caja_sesion_id"), ["sesion_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_movimiento_caja_tipo"), ["tipo"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movimiento_caja", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movimiento_caja_tipo"))
        batch_op.drop_index(batch_op.f("ix_movimiento_caja_sesion_id"))
        batch_op.drop_index(batch_op.f("ix_movimiento_caja_medio_pago_id"))
        batch_op.drop_index(batch_op.f("ix_movimiento_caja_documento_id"))

    op.drop_table("movimiento_caja")
    with op.batch_alter_table("sesion_caja", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sesion_caja_fecha_apertura"))
        batch_op.drop_index(batch_op.f("ix_sesion_caja_estado"))

    op.drop_table("sesion_caja")
    with op.batch_alter_table("medio_pago", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medio_pago_nombre"))

    op.drop_table("medio_pago")
    # ### end Alembic commands ###
