"""base: sucursal, usuario, auditoria

Revision ID: d83bd0bb263c
Revises:
Create Date: 2026-08-20 21:52:21.475821

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 — lo usa el repr de JSONB
from sqlalchemy.dialects import postgresql, sqlite

import app.core.types  # noqa: F401 — UUIDType y FlexibleJSON en las columnas

revision: str = "d83bd0bb263c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sucursal",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "LOCAL", "DEPOSITO", name="tiposucursal", native_enum=False, length=10
            ),
            nullable=False,
        ),
        sa.Column("direccion", sa.String(length=200), nullable=True),
        sa.Column("localidad", sa.String(length=100), nullable=True),
        sa.Column("provincia", sa.String(length=100), nullable=True),
        sa.Column("telefono", sa.String(length=30), nullable=True),
        sa.Column("punto_venta_arca", sa.Integer(), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sucursal", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sucursal_codigo"), ["codigo"], unique=True)

    op.create_table(
        "usuario",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "rol",
            sa.Enum(
                "ADMIN",
                "ENCARGADO",
                "VENDEDOR",
                name="rolusuario",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("sucursal_id", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("ultimo_ingreso", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sucursal_id"], ["sucursal.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usuario_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_usuario_rol"), ["rol"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_usuario_sucursal_id"), ["sucursal_id"], unique=False
        )

    op.create_table(
        "audit_log",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("tabla_afectada", sa.String(length=50), nullable=False),
        sa.Column("registro_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column(
            "operacion",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "DELETE",
                name="operacionaudit",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "datos_anteriores",
            postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "datos_nuevos",
            postgresql.JSONB(astext_type=Text()).with_variant(sqlite.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("usuario_id", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("ip_origen", sa.String(length=45), nullable=True),
        sa.Column(
            "ts",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuario.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_log_operacion"), ["operacion"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_registro_id"), ["registro_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_tabla_afectada"), ["tabla_afectada"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_log_ts"), ["ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_usuario_id"), ["usuario_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_log_tabla_afectada"))
        batch_op.drop_index(batch_op.f("ix_audit_log_registro_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_operacion"))

    op.drop_table("audit_log")
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usuario_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_usuario_rol"))
        batch_op.drop_index(batch_op.f("ix_usuario_email"))

    op.drop_table("usuario")
    with op.batch_alter_table("sucursal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sucursal_codigo"))

    op.drop_table("sucursal")
    # ### end Alembic commands ###
