"""stock: existencias y movimientos

Revision ID: c4f660e5ef43
Revises: eb427fbc170c
Create Date: 2026-08-23 19:07:58.888252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 — lo usa el repr de JSONB

import app.core.types  # noqa: F401 — UUIDType y FlexibleJSON en las columnas

revision: str = "c4f660e5ef43"
down_revision: str | None = "eb427fbc170c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movimiento_stock",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("variante_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("sucursal_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "INGRESO",
                "AJUSTE",
                "VENTA",
                "DEVOLUCION",
                "TRANSFERENCIA_SALIDA",
                "TRANSFERENCIA_ENTRADA",
                "CONTEO",
                name="tipomovimiento",
                native_enum=False,
                length=25,
            ),
            nullable=False,
        ),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("cantidad_resultante", sa.Integer(), nullable=False),
        sa.Column("motivo", sa.String(length=200), nullable=True),
        sa.Column(
            "documento_tipo",
            sa.Enum(
                "VENTA",
                "DEVOLUCION",
                "CAMBIO",
                "TRANSFERENCIA",
                "COMPRA",
                "CONTEO",
                name="tipodocumento",
                native_enum=False,
                length=15,
            ),
            nullable=True,
        ),
        sa.Column("documento_id", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sucursal_id"], ["sucursal.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["variante_id"], ["variante.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movimiento_stock", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movimiento_stock_documento_id"),
            ["documento_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_movimiento_stock_sucursal_id"), ["sucursal_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_movimiento_stock_tipo"), ["tipo"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_movimiento_stock_variante_id"), ["variante_id"], unique=False
        )
        batch_op.create_index(
            "ix_movimiento_variante_sucursal",
            ["variante_id", "sucursal_id"],
            unique=False,
        )

    op.create_table(
        "stock",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("variante_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("sucursal_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("stock_minimo", sa.Integer(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sucursal_id"], ["sucursal.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["variante_id"], ["variante.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "variante_id", "sucursal_id", name="uq_stock_variante_sucursal"
        ),
    )
    with op.batch_alter_table("stock", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_sucursal_id"), ["sucursal_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_variante_id"), ["variante_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_variante_id"))
        batch_op.drop_index(batch_op.f("ix_stock_sucursal_id"))

    op.drop_table("stock")
    with op.batch_alter_table("movimiento_stock", schema=None) as batch_op:
        batch_op.drop_index("ix_movimiento_variante_sucursal")
        batch_op.drop_index(batch_op.f("ix_movimiento_stock_variante_id"))
        batch_op.drop_index(batch_op.f("ix_movimiento_stock_tipo"))
        batch_op.drop_index(batch_op.f("ix_movimiento_stock_sucursal_id"))
        batch_op.drop_index(batch_op.f("ix_movimiento_stock_documento_id"))

    op.drop_table("movimiento_stock")
    # ### end Alembic commands ###
