"""catalogo: marcas, talles, colores, categorias, productos, variantes, precios

Revision ID: eb427fbc170c
Revises: d83bd0bb263c
Create Date: 2026-08-20 22:28:41.771430

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 — lo usa el repr de JSONB

import app.core.types  # noqa: F401 — UUIDType y FlexibleJSON en las columnas

revision: str = "eb427fbc170c"
down_revision: str | None = "d83bd0bb263c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "color",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("codigo_hex", sa.String(length=7), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("color", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_color_nombre"), ["nombre"], unique=True)

    op.create_table(
        "curva_talle",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("curva_talle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_curva_talle_nombre"), ["nombre"], unique=True
        )

    op.create_table(
        "marca",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("marca", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_marca_nombre"), ["nombre"], unique=True)

    op.create_table(
        "categoria",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("curva_talle_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["curva_talle_id"], ["curva_talle.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("categoria", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categoria_curva_talle_id"), ["curva_talle_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_categoria_nombre"), ["nombre"], unique=True
        )

    op.create_table(
        "talle",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("curva_talle_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("valor", sa.String(length=10), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["curva_talle_id"], ["curva_talle.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("curva_talle_id", "valor", name="uq_talle_curva_valor"),
    )
    with op.batch_alter_table("talle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_talle_curva_talle_id"), ["curva_talle_id"], unique=False
        )

    op.create_table(
        "producto",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("categoria_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("marca_id", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "genero",
            sa.Enum(
                "HOMBRE",
                "MUJER",
                "UNISEX",
                "NINO",
                "NINA",
                "BEBE",
                name="genero",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "temporada",
            sa.Enum(
                "VERANO",
                "INVIERNO",
                "ENTRETIEMPO",
                "ATEMPORAL",
                name="temporada",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"], ["categoria.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["marca_id"], ["marca.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("producto", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_producto_categoria_id"), ["categoria_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_producto_marca_id"), ["marca_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_producto_nombre"), ["nombre"], unique=False
        )

    op.create_table(
        "imagen_producto",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("producto_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("clave", sa.String(length=255), nullable=False),
        sa.Column("nombre_original", sa.String(length=255), nullable=True),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["producto_id"], ["producto.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave"),
    )
    with op.batch_alter_table("imagen_producto", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_imagen_producto_producto_id"), ["producto_id"], unique=False
        )

    op.create_table(
        "variante",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("producto_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("talle_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("color_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("codigo_barras", sa.String(length=50), nullable=True),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["color_id"], ["color.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["producto_id"], ["producto.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["talle_id"], ["talle.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "producto_id",
            "talle_id",
            "color_id",
            name="uq_variante_producto_talle_color",
        ),
    )
    with op.batch_alter_table("variante", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_variante_codigo_barras"), ["codigo_barras"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_variante_color_id"), ["color_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_variante_producto_id"), ["producto_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_variante_sku"), ["sku"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_variante_talle_id"), ["talle_id"], unique=False
        )

    op.create_table(
        "precio",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("variante_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("costo", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("precio_venta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("precio_mayorista", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "vigente_desde",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("vigente_hasta", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo", sa.String(length=200), nullable=True),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["variante_id"], ["variante.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("precio", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_precio_variante_id"), ["variante_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_precio_vigente_desde"), ["vigente_desde"], unique=False
        )
        batch_op.create_index(
            "uq_precio_vigente_por_variante",
            ["variante_id"],
            unique=True,
            postgresql_where=sa.text("vigente_hasta IS NULL"),
            sqlite_where=sa.text("vigente_hasta IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("precio", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_precio_vigente_por_variante",
            postgresql_where=sa.text("vigente_hasta IS NULL"),
            sqlite_where=sa.text("vigente_hasta IS NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_precio_vigente_desde"))
        batch_op.drop_index(batch_op.f("ix_precio_variante_id"))

    op.drop_table("precio")
    with op.batch_alter_table("variante", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_variante_talle_id"))
        batch_op.drop_index(batch_op.f("ix_variante_sku"))
        batch_op.drop_index(batch_op.f("ix_variante_producto_id"))
        batch_op.drop_index(batch_op.f("ix_variante_color_id"))
        batch_op.drop_index(batch_op.f("ix_variante_codigo_barras"))

    op.drop_table("variante")
    with op.batch_alter_table("imagen_producto", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_imagen_producto_producto_id"))

    op.drop_table("imagen_producto")
    with op.batch_alter_table("producto", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_producto_nombre"))
        batch_op.drop_index(batch_op.f("ix_producto_marca_id"))
        batch_op.drop_index(batch_op.f("ix_producto_categoria_id"))

    op.drop_table("producto")
    with op.batch_alter_table("talle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_talle_curva_talle_id"))

    op.drop_table("talle")
    with op.batch_alter_table("categoria", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categoria_nombre"))
        batch_op.drop_index(batch_op.f("ix_categoria_curva_talle_id"))

    op.drop_table("categoria")
    with op.batch_alter_table("marca", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marca_nombre"))

    op.drop_table("marca")
    with op.batch_alter_table("curva_talle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_curva_talle_nombre"))

    op.drop_table("curva_talle")
    with op.batch_alter_table("color", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_color_nombre"))

    op.drop_table("color")
    # ### end Alembic commands ###
