"""ventas: articulos, ventas y lineas

Revision ID: 3419de40e436
Revises: c2ff5eb438c9
Create Date: 2026-08-24 19:38:35.649051

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 — lo usa el repr de JSONB

import app.core.types  # noqa: F401 — UUIDType y FlexibleJSON en las columnas

revision: str = "3419de40e436"
down_revision: str | None = "c2ff5eb438c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articulo",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("categoria", sa.String(length=50), nullable=True),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("articulo", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_articulo_categoria"), ["categoria"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_articulo_nombre"), ["nombre"], unique=True)

    op.create_table(
        "venta",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("sesion_caja_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "REGISTRADA",
                "ANULADA",
                name="estadoventa",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column(
            "fecha",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("registrada_por", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("anulada_por", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("fecha_anulacion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_anulacion", sa.String(length=200), nullable=True),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sesion_caja_id"], ["sesion_caja.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("venta", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_venta_estado"), ["estado"], unique=False)
        batch_op.create_index(batch_op.f("ix_venta_fecha"), ["fecha"], unique=False)
        batch_op.create_index(batch_op.f("ix_venta_numero"), ["numero"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_venta_sesion_caja_id"), ["sesion_caja_id"], unique=False
        )

    op.create_table(
        "linea_venta",
        sa.Column("id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("venta_id", app.core.types.UUIDType(length=36), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column("articulo_id", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("descripcion", sa.String(length=200), nullable=False),
        sa.Column("talle", sa.String(length=15), nullable=True),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column("updated_by", app.core.types.UUIDType(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["articulo_id"], ["articulo.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["venta_id"], ["venta.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venta_id", "numero", name="uq_linea_venta_numero"),
    )
    with op.batch_alter_table("linea_venta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_linea_venta_articulo_id"), ["articulo_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_linea_venta_venta_id"), ["venta_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte la migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linea_venta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_linea_venta_venta_id"))
        batch_op.drop_index(batch_op.f("ix_linea_venta_articulo_id"))

    op.drop_table("linea_venta")
    with op.batch_alter_table("venta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_venta_sesion_caja_id"))
        batch_op.drop_index(batch_op.f("ix_venta_numero"))
        batch_op.drop_index(batch_op.f("ix_venta_fecha"))
        batch_op.drop_index(batch_op.f("ix_venta_estado"))

    op.drop_table("venta")
    with op.batch_alter_table("articulo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_articulo_nombre"))
        batch_op.drop_index(batch_op.f("ix_articulo_categoria"))

    op.drop_table("articulo")
    # ### end Alembic commands ###
